### ISSUE TITLE
Make the graph div responsive in the demo.

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/spectral-workbench.js#104]
@jywarren Can we have this as a first-timers-only issue?

Only some media queries have to be implemented in the `capture.css` file in the `examples/capture` directory.

**Comment by jywarren** [comment]
This would be SUPER! Please go ahead and open one and we can review!

**Comment by sidntrivedi012** [comment]
Sure, making one. Thanks 😃

**Comment by sidntrivedi012** [comment]
Opened a fto issue here - #110 . Thanks.
