### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/spectral-workbench.js#105]
@jywarren Should we add a CoC in this project?

**Comment by sidntrivedi012** [comment]
We can display it as a first-timers issue? Not for the discussion but the implementation part?

**Comment by jywarren** [comment]
This would be really nice! 

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by sidntrivedi012** [comment]
I think I should solve this issue myself since its not wise for someone to add code of conduct as a first timer. Indeed, a project should have it there beforehand. Thus, adding one myself. Thanks!

**Comment by jywarren** [comment]
Ok, that makes sense! Thanks!

**Comment by starkblaze01** [comment]
Merged #127
