### ISSUE TITLE
Add npm version badge to the README.

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/spectral-workbench.js#111]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
  - [ ] **🙋 Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  - [ ] **📝 Update** 

  - [ ] **💾 Commit your changes**

 - [ ]  **🔀 Start a Pull Request.** There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

  - [ ] **🏁 Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

**Comment by sidntrivedi012** [comment]
Adding badges to the readme gives first-timers and old-timers an at-a-glance peek into the status of the project.

Thus, in order to add a badge, you can checkout some badges and their customizations here - https://shields.io/category/version.

Also, the npm package of `spectra-workbench.js` can be found here - https://www.npmjs.com/package/spectral-workbench

Thanks 🎉 🎈 🔬 💯

**Comment by zlv2s** [comment]
Hi may i claim this issue

**Comment by sidntrivedi012** [comment]
Hey @zlv2s , thanks for reaching out. Sure, go ahead. 👍

**Comment by zlv2s** [comment]
Thanks. I'm new at PR, still learning the workflow ☺️

**Comment by sidntrivedi012** [comment]
Sure, @zlv2s . It was great that you sent the PR from a different branch than the main branch of your fork. Also, there are many first-timers-issues in many other awesome projects of Public Lab waiting to be solved. You can find them in our Community Toolbox here - https://code.publiclab.org . Go ahead.

Thanks. 🎉 💯
