### ISSUE TITLE
Add Contributing Guide to the project.

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/spectral-workbench.js#126]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
  - [ ] **🙋 Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  - [ ] **📝 Update** 

  - [ ] **💾 Commit your changes**

 - [ ]  **🔀 Start a Pull Request.** There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

  - [ ] **🏁 Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

**Comment by BenKalungi** [comment]
Is someone working on this already???

**Comment by BenKalungi** [comment]
I would love to claim this issue, where's the file

**Comment by sidntrivedi012** [comment]
Hey @BenKalungi ,

So glad that you reached out. I had already made a patch for this issue. But, we have a lot of issues in which we need help. Can you please take a look at #110 ?

Also, you can find more first timer issues at code.publiclab.org.

Thanks. 🎉 👍

**Comment by gaddeharsha13** [comment]
Hi is this issue still open? Can I claim it?

**Comment by AtharvaSune** [comment]
Hi, is this issue still open?

**Comment by sidntrivedi012** [comment]
Hey @gaddeharsha13 @AtharvaSune , really great that you reached out. I had already made a patch for this issue. But, we have a lot of issues in which we need help. Can you please take a look at #110 ?

Also, you can find more first timer issues at https://code.publiclab.org.

Thanks. 🎉 👍

**Comment by akiraro** [comment]
Hi, is this issue still open ?

**Comment by Askat08** [comment]
Hi there, i'd like to tackle this issue if it's still available or any available issues for beginner.

**Comment by sidntrivedi012** [comment]
Hey @akiraro and @Askat08, thanks a lot for reaching out to contribute. This issue has been fixed in #127. But, don't worry we have a lot of issues where we need help. You can check them out here or at https://code.publiclab.org. There are many `first-timers-only` issues waiting to get solved.

Thanks. 🎉 🎈

**Comment by Neilblaze** [comment]
Heya @sidntrivedi012 I can see that this issue has been tagged as fto regarding GCI. As you have said that this issue has been fixed before a while in #127 , so for now can you suggest me some tasks or issues that can be solved by a newbie regarding GCI'19? :D

**Comment by starkblaze01** [comment]
Merged #127
