### ISSUE TITLE
Update Issue Template

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/spectral-workbench.js#129]
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

Github has changed the issue template workflow. Thus, we need to make the required changes in our template.

![Screenshot 2019-09-09 at 3 00 27 PM](https://user-images.githubusercontent.com/31186013/64519871-9b4e9000-d312-11e9-8100-c853c10a4c7e.png)

Thanks.

**Comment by AtharvaSune** [comment]
Hi , I would like to work on this issue

**Comment by subhamX** [comment]
@AtharvaSune @sidntrivedi012 Can I work on this issue if it is not yet resolved.

**Comment by alexido19** [comment]
Hello @sidntrivedi012 can I work on this issue if its not been resolved ?

**Comment by sidntrivedi012** [comment]
Hey @discombobulateme , I already see a PR for this issue at #131 . 

Though, don't worry there are a lot of issues where we need help. You can go to our Community Toolbox (https://code.publiclab.org) and find many first-timers-only issues there filtered by projects.

Thanks for reaching out. 🙂 🎈

**Comment by starkblaze01** [comment]
Uploaded on GCI dashboard

**Comment by SidharthBansal** [comment]
Please suggest a reason for 2 instance count. Instance count means number of people needed to solve this issue. Also, please label `beginner` too.
Thanks

**Comment by starkblaze01** [comment]
Hi, @SidharthBansal. The issue Template for this repository needs to be updated. There might be multiple suggestions and one may be better than others. It will be great to see two students working on it and come up with a better template.

**Comment by SidharthBansal** [comment]
PUBLISHED ON GCI DASHBOARD

**Comment by ananyaarun** [comment]
Hey @SidharthBansal , I just opened a new issue for this and realized this was  already published.
This still is not the latest templates.
Can we follow these #147 ?
this has the latest changes as in plots2
Thanks!

**Comment by SidharthBansal** [comment]
Thanks
