### ISSUE TITLE
Break capture.js into small function modules and refactor it.

### ISSUE THREAD

**Issue by starkblaze01** [publiclab/spectral-workbench.js#141]
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

Code Refactoring is a process of application's restructuring which optimizes its internal structure, but leaves its basic functionality untouched. Being a component of framework development, refactoring can cause difficult-to-detect bugs due to incorrect utilization.

Currently [capture.js](https://github.com/publiclab/spectral-workbench.js/blob/main/examples/capture/capture.js) has 700+ LOC which is not a good practice. It's function modules needs to be broken down into small files and should be used by importing in the `captutre.js` file without breaking any of the current functionalities. Try creating a separate files one by one for functions and import it in `capture.js`, and do testing along with it.

**Comment by starkblaze01** [comment]
Uploaded on GCI dashboard

**Comment by SidharthBansal** [comment]
Please suggest me a reason for higher instance count?

**Comment by starkblaze01** [comment]
Hi, @SidharthBansal. I have kept a higher instance count because of the complexity of code and number of lines. It may so happen a student may not be able to refactor and create separate files for all the functions and then import it. So, he may partially refactor a few parts of the code. But if you think instance count is high I can lower it down. Will 2 be okay?

**Comment by SidharthBansal** [comment]
PUBLISHED ON GCI DASHBOARD

**Comment by jywarren** [comment]
This is done in https://github.com/publiclab/spectral-workbench.js/pull/148! 

OK - next step - let's see -- we actually want all the code in one file, ultimately. What we can do is to install grunt and set up a compilation step that merges these files. That way the source files can be in the /src/ directory and the combined output file can be in /dist/.

This may sound like a lot but it's not too hard to set up. There is a good example in this library with documentation on how to use grunt to "build" or "compile" the source files.

https://github.com/publiclab/inline-markdown-editor#contributing

Would someone like to take this on? we could open this in a new issue with the above description, titled `Get capture.js subfiles compiling into a single file using Grunt`

**Comment by sidntrivedi012** [comment]
@jywarren I would like to work on this.

**Comment by starkblaze01** [comment]
Great @sidntrivedi012 , well I was thinking of creating it as a new gci-candidate issue. But if you would like to work on this then it's fine. Should I remove the label from the new issue here: #151 ?

**Comment by sidntrivedi012** [comment]
@starkblaze01 Sure, I didn't see the gci-candidate label. It will be great if someone would like to work on it. If no one shows up, I would love to help out. Thanks.

**Comment by jywarren** [comment]
Hi all! Awesome, thank you!!!

This will make it much easier to get small, discrete upgrades that'll make
good FTOs or just generally easier to review changes. Like upgrading a
version number or swapping in an existing library for a function we
wrote custom.
