### ISSUE TITLE
Get capture.js subfiles compiling into a single file using Grunt

### ISSUE THREAD

**Issue by starkblaze01** [publiclab/spectral-workbench.js#151]
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

We have a file [capture.js](https://github.com/publiclab/spectral-workbench.js/blob/main/examples/capture/capture.js) which is now refactored here in this [PR](https://github.com/publiclab/spectral-workbench.js/pull/148). Here are the new imports in [index.html](https://github.com/publiclab/spectral-workbench.js/blob/5e54176b66b13b47d791253986371981d43b6bee/examples/capture/index.html#L26) file.
Now we actually want all the code in one file after getting compiled. What we can do is to install grunt and set up a compilation step that merges these files. That way the source files can be in the /src/ directory and the combined output file can be in /dist/.

This may sound like a lot but it's not too hard to set up. There is a good example in this library with documentation on how to use grunt to "build" or "compile" the source files.
https://github.com/publiclab/inline-markdown-editor#contributing

@jywarren @sidntrivedi012

**Comment by starkblaze01** [comment]
Uploaded on GCI dashboard

**Comment by SidharthBansal** [comment]
published

**Comment by pythongiant** [comment]
I'll work on this @SidharthBansal

**Comment by SidharthBansal** [comment]
Great thanks
