### ISSUE TITLE
Update getUserMedia WebRTC library for broader browser compatibility (+ iOS)

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench.js#87]
http://publiclab.org/spectral-workbench#Browsers lists:

> Spectral Workbench should work on Chrome (in Windows/Mac/Linux/Android, but not iOS), Firefox (Windows/Mac/Linux/Android), or Opera (Android). It may work on other browsers and we are working on expanding coverage; read more on this page:

Linking here; we should be able to support:

* [ ] Safari desktop
* [ ] iOS (soon, as we hear getUserMedia is now supported on iOS???)

Let's discuss/plan/collect information here!

This would also be possible to port back to https://github.com/publiclab/spectral-workbench/ once implemented here.

**Comment by jywarren** [comment]
Relates to: https://github.com/publiclab/spectral-workbench/issues/104, https://github.com/publiclab/spectral-workbench/issues/353, #71

**Comment by sidntrivedi012** [comment]
@jywarren I found out that the camera capture is not working on firefox quantum as well as the firefox nightly browser. Implement this cross-browser compatibility is very important since a lot of people don't use Chrome/Chromium since these browsers are quite heavy to work on their machine.

Please guide me as to how to implement this. Would like to work on it.

**Comment by sidntrivedi012** [comment]
![Peek 2019-03-29 20-33](https://user-images.githubusercontent.com/31186013/55242065-78e42100-5262-11e9-8fad-66ec8fb9bb2e.gif)

**Comment by sidntrivedi012** [comment]
The camera was not starting even after giving it the permission. An error was popping up in the console - `navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia`

**Comment by jywarren** [comment]
Hi! I think we need to identify a replacement for the getUserMedia shim we're using here:

https://github.com/publiclab/spectral-workbench.js/blob/a062b8d45bacfe5e2c202a3a60deca8c60d9c65c/examples/capture/index.html#L18

https://github.com/publiclab/spectral-workbench.js/blob/a062b8d45bacfe5e2c202a3a60deca8c60d9c65c/package.json#L32

There are a number of other shim libraries out there. Let's find one that's really well supported, and migrate to it. Some even support iOS, i believe! 

https://duckduckgo.com/?q=github+getusermedia&atb=v121-6&ia=web

This one is worth testing out: https://webrtc.github.io/samples/src/content/getusermedia/gum/

https://github.com/webrtc/samples/tree/gh-pages/src/content/getusermedia/gum

See it working in iOS here! https://github.com/processing/p5.js/issues/2146

**Comment by jywarren** [comment]
@sidntrivedi012 I was wondering if you'd consider prioritizing the part of your project which updates the getUserMedia component? Because a recent change in Chrome for Android means we can no longer switch from the front camera to the back camera on a smartphone. So, people using these papercraft spectrometers now have a much harder time: https://publiclab.org/papercraft-spectrometer

**Comment by jywarren** [comment]
Either by trying to get an early version of your project using this fix to production in "beta" mode sooner, or, potentially trying to apply the fix to the existing codebase in parallel to developing the stand-alone library. I'm not sure what would be better?

**Comment by jywarren** [comment]
@sidntrivedi012 would you try this code to get this working on iOS?

https://github.com/processing/p5.js/pull/2147/files

**Comment by jywarren** [comment]
Do you have a version of Safari on iOS or Mac os to test?

**Comment by jywarren** [comment]
Here's a great article on webrtc adapters and what they're for! 

https://bloggeek.me/webrtc-adapter-js/amp/

**Comment by sidntrivedi012** [comment]
@jywarren I would like to work on it. Have also made a PR at #125. Can we start work on it again?

**Comment by jywarren** [comment]
Sure, i'll take a look at that today, thanks!

**Comment by jywarren** [comment]
This was solved by @chukohsin + team in #172 by using https://github.com/Temasys/AdapterJS !
