### ISSUE TITLE
PLANNING ISSUE : Spectral Workbench Capture

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/spectral-workbench.js#92]
Planning issue for the roadmap to completing the Spectral Workbench Capture project.

The major tasks to be implemented are as follow:
- [x] Refactoring and Integration
- [x] Testing
- [x] Consolidation and Testing of API for search, matching, etc.
- [x] Making an npm module
- [x] Development of React app around basic ui modules .

However, I will also be dividing these major tasks into subtasks in order to make the tracking of progress easy.

@jywarren @Harshithpabbati Please have a look at this and suggest as to what more should I add and how to start the work further. :slightly_smiling_face:

**Comment by SidharthBansal** [comment]
Thanks @sidntrivedi012 for opening up a planning issue. It will be great if you can break this issues so that we can introduce modularity and fix things in baby steps.

**Comment by SidharthBansal** [comment]
Please add appropriate labels like `gsoc` etc.

**Comment by sidntrivedi012** [comment]
@SidharthBansal I think I don't have the access to add labels. The option to add labels is not popping up.

**Comment by Harshithpabbati** [comment]
Mmm wait let @jywarren add you to the collaborator. So that you will have access to add labels.

**Comment by sidntrivedi012** [comment]
Sure. @Harshithpabbati :+1:

**Comment by Dhiraj240** [comment]
@sidntrivedi012 Have you thought of sub-dividing the above tasks? The coding period is near and as per your proposal work on dividing "Refactoring and Integration" task, so that you can start efficiently.

**Comment by jywarren** [comment]
I've added you all as collaborators! And, I hope this makes sense but I protected the main branch. Let's be sure to get reviews from me for at least the first few merges to main as we get used to the workflow. Sound good? Thanks all!

**Comment by jywarren** [comment]
also noting https://github.com/publiclab/plots2/issues/5794 as we get organized!

**Comment by starkblaze01** [comment]
> I've added you all as collaborators! And, I hope this makes sense but I protected the main branch. Let's be sure to get reviews from me for at least the first few merges to main as we get used to the workflow. Sound good? Thanks all!

Yeah sure @jywarren . 
And, I guess Cross Domain Session in production is working fine with SWB PR being merged?

**Comment by jywarren** [comment]
I wanted to note that we could do some more granular task listing here. Maybe:

* [ ] resolving basic bugs with current local capture (starting with #95)
* [ ] publishing `gh-pages` demo of capture working!
* [ ] starting a new branch where the `/examples/capture/capture.js` code is compiled in https://github.com/publiclab/spectral-workbench.js/tree/main/src, in a file called `SpectralWorkbench.Capture.js`, and saved to `/dist/` alongside other compiled files
* [ ] pointing the demo at the new /dist/ compiled code
* [ ] ensuring it works in gh-pages
* [ ] starting to chop up the code in `SpectralWorkbench.Capture.js` into sub-files, using the `require()` method (I recommend this post! https://ponyfoo.com/articles/modular-design-thinking) starting with just one sub-file and confirming that the demo works
* [ ] repeating to logically break up the big file into smaller chunks, like has been done with existing code! Aim for <100 lines per file and "one purpose per file" roughly

This is a good bit! What do you think???

**Comment by sidntrivedi012** [comment]
Sure @jywarren. This will be really helpful. Thanks a ton. 🎉

**Comment by starkblaze01** [comment]
> I wanted to note that we could do some more granular task listing here. Maybe:
> 
> * [ ]  resolving basic bugs with current local capture (starting with #95)
> * [ ]  publishing `gh-pages` demo of capture working!
> * [ ]  starting a new branch where the `/examples/capture/capture.js` code is compiled in https://github.com/publiclab/spectral-workbench.js/tree/main/src, in a file called `SpectralWorkbench.Capture.js`, and saved to `/dist/` alongside other compiled files
> * [ ]  pointing the demo at the new /dist/ compiled code
> * [ ]  ensuring it works in gh-pages
> * [ ]  starting to chop up the code in `SpectralWorkbench.Capture.js` into sub-files, using the `require()` method (I recommend this post! https://ponyfoo.com/articles/modular-design-thinking) starting with just one sub-file and confirming that the demo works
> * [ ]  repeating to logically break up the big file into smaller chunks, like has been done with existing code! Aim for <100 lines per file and "one purpose per file" roughly
> 
> This is a good bit! What do you think???

Sounds great @jywarren ,
Also, @sidntrivedi012 make sure to create small modules one by one according to functionality and replace it by exporting in the file, and after testing the module move on to next function to make it easy to trace back for any errors while implementing.

**Comment by sidntrivedi012** [comment]
Ok @starkblaze01 . 👍

**Comment by jywarren** [comment]
This is looking great in the gh-pages demo! https://publiclab.github.io/spectral-workbench.js/examples/capture/

![image](https://user-images.githubusercontent.com/24359/61553716-0f626b00-aa29-11e9-96ec-18dad674a8c2.png)

Seems like the download button isn't working, however?

**Comment by sidntrivedi012** [comment]
@jywarren Should I open an issue for it and try solving it?

**Comment by sidntrivedi012** [comment]
@jywarren Also, I need help for solving #75. I am facing an error when using the infragram code in capture's html file. I have mentioned the error here - https://github.com/publiclab/spectral-workbench.js/issues/75 as well on the gitter channel. Please take a look. Thanks 🙂
